### ISSUE TITLE
Add misc. matches with unit conversions

### ISSUE THREAD

**Issue by cmutel** [fjuniorr/flowmapper#24]
```python
{
    'Ammonia, as N': {
        'name': 'Ammonia',
        'multiplier': 17 / 14,
    },
    'Gas, mine, off-gas, process, coal mining/kg': {
        'name': 'Gas, mine, off-gas, process, coal mining',
        'mutiplier': 1, #TBD
    },
    'AOX (Adsorbable Organic Halogens)': {
        'name': 'AOX, Adsorbable Organic Halogen as Cl',
        'mutiplier': 1, #TBD
    },
    'AOX, Adsorbable Organic Halogen': {
        'name': 'AOX, Adsorbable Organic Halogen as Cl',
        'mutiplier': 1, #TBD
    },
}
```

**Comment by fjuniorr** [comment]
@cmutel I've added a very crude strategy to allow for passing information about unit conversions in https://github.com/fjuniorr/flowmapper/pull/32 for the flows in this list but I don't feel this is the right path in general.

**Comment by cmutel** [comment]
> I don't feel this is the right path in general

I hear that. I think we will need a common set of unit conversions (e.g. g -> kg, ton -> kg, MJ -> kWh), and some manual mapping lists (this is ugly but inevitable, at least for now).

Let's agree to come back to this later.
