### ISSUE TITLE
Add docstrings to `Flowmap`

### ISSUE THREAD

**Issue by fjuniorr** [fjuniorr/flowmapper#61]
In retrospect I should've practiced more [documentation-driven development](https://gist.github.com/zsup/9434452) for the more public facing classes. `Flowmap` is one that would benefit from this.

**Comment by cmutel** [comment]
OK to go ahead with this. Please follow our [common style guidelines](https://docs.brightway.dev/en/latest/content/contributing/code.html#docstrings).
