### ISSUE TITLE
Double check implemented matching rules

### ISSUE THREAD

**Issue by fjuniorr** [fjuniorr/flowmapper#8]
- integrity issues with mappings where two FK are not PK in junction table
- cas numbers match conditions (eg. zync)
- match for https://commonchemistry.cas.org/results?q=Metaldehyde

**Comment by fjuniorr** [comment]
@cmutel here are a more detailed notes on the topics above.

## integrity issues with mappings where two FK are not PK in junction table

I was not able to reproduce this. In the process of investigating I've added a useful summary of the mappings cardinalities in https://github.com/fjuniorr/flowmapper/commit/7f9fdb55bdd16b72942ed2a9451c891e48dcda4b:

```python
from flowmapper.utils import read_field_mapping, read_flowlist
from flowmapper.flowmap import Flowmap
from flowmapper.flow import Flow

fields = read_field_mapping('config/simapro-ecoinvent.py')
source_flows = [Flow.from_dict(flow, fields['source']) for flow in read_flowlist('data/agribalyse-3.1.1-biosphere.json')]
target_flows = [Flow.from_dict(flow, fields['target']) for flow in read_flowlist('data/ecoinvent-3.7-biosphere.json')]

flowmap = Flowmap(source_flows, target_flows)
flowmap.mappings
flowmap.statistics()
```

```python
5667 source flows...
4329 target flows...
3422 mappings (59.75% of total).
Mappings cardinalities: {'N:1': 1753, '1:1': 1598, 'N:M': 48, '1:N': 23}
```

## cas numbers match conditions (eg. zync)

In [Match - Validated CAS numbers.ipynb](https://github.com/brightway-lca/simapro_ecoinvent_elementary_flows/blob/main/Notebooks/Match%20-%20Validated%20CAS%20numbers.ipynb) CAS numbers that are not valid are discarded. However, in [`match_identical_cas_numbers`](https://github.com/fjuniorr/flowmapper/blob/cdb8eaf3ef92a5b50fde74d54bd3f9bf9b770e34/flowmapper/match.py#L46-L49) if the CAS number and the context are equal, it's considered a match.  Is this behaviour problematic?

## match for https://commonchemistry.cas.org/results?q=Metaldehyde

To be honest I don't remember how or why I saw this because I'm not doing this type of verification. We have the match:

```json
  {
    "source": {
      "name": "Metaldehyde (tetramer)",
      "categories": [
        "Emissions to soil",
        "agricultural"
      ],
      "unit": "kg"
    },
    "target": {
      "uuid": "597847df-518f-4bd6-ae50-1de01f2761a4",
      "name": "Metaldehyde",
      "context": "soil/agricultural",
      "unit": "kg"
    },
    "conversion_factor": 1.0,
    "comment": "Minor random name differences"
  }
```

From [SimaProv9.4.csv](https://github.com/brightway-lca/simapro_ecoinvent_elementary_flows/blob/main/Mapping/Input/Flowlists/SimaProv9.4.csv) I saw that the CAS for _Metaldehyde (tetramer)_ is _000108-62-3_ while for _Metaldehyde_ (`597847df-518f-4bd6-ae50-1de01f2761a4`) it's _009002-91-9_ which would indicate they are different flows? If that's the case does it make sense to enrich Simapro flows with the CAS number before doing matching with ecoinvent to find similar problems?

**Comment by fjuniorr** [comment]
@cmutel if we don't need to have 100% correct mappings maybe I can close this until it becomes a problem?

**Comment by cmutel** [comment]
> In [Match - Validated CAS numbers.ipynb](https://github.com/brightway-lca/simapro_ecoinvent_elementary_flows/blob/main/Notebooks/Match%20-%20Validated%20CAS%20numbers.ipynb) CAS numbers that are not valid are discarded. However, in [match_identical_cas_numbers](https://github.com/fjuniorr/flowmapper/blob/cdb8eaf3ef92a5b50fde74d54bd3f9bf9b770e34/flowmapper/match.py#L46-L49) if the CAS number and the context are equal, it's considered a match. Is this behaviour problematic?

Honestly, humans, get you shit together... I am fine with however this is currently handled, this should be undefined behaviour. Do two wrongs make a right?

**Comment by cmutel** [comment]
> If that's the case does it make sense to enrich Simapro flows with the CAS number before doing matching with ecoinvent to find similar problems?

This is an excellent idea, let's make this an option in the config.

**Comment by fjuniorr** [comment]
> Honestly, humans, get you shit together... I am fine with however this is currently handled, this should be undefined behaviour. Do two wrongs make a right?

:laughing: 

I will leave this as is then (ie. invalid CAS numbers that are equal it's considered a match)



> > If that's the case does it make sense to enrich Simapro flows with the CAS number before doing matching with ecoinvent to find similar problems?
> 
> This is an excellent idea, let's make this an option in the config.

I've created https://github.com/fjuniorr/flowmapper/issues/74 to track this and I'm closing this issue.
